# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        packages:
            favicon:
                base_path: favicon/
            images_static:
                base_path: images/static/
            images_dynamic:
                base_path: images/dynamic/
            product_images:
                base_path: images/dynamic/products/
            delivery_method_images:
                base_path: images/dynamic/delivery-methods/
            payment_method_images:
                base_path: images/dynamic/payment-methods/

    uid:
        default_uuid_version: 4

when@prod:
    framework:
        error_controller: App\Controller\ErrorController::showError

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file