twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'fragments/form_themes/_materialize.html.twig'
    globals:
        vat_payer: '%app_vat_payer%'
        site_name: '%app_site_name%'
        site_phone: '%app_site_phone%'
        site_email: '%app_site_email%'
        site_facebook: '%app_site_facebook%'
        site_instagram: '%app_site_instagram%'
        navbar_service: '@app.navbar_service'

when@test:
    twig:
        strict_variables: true