twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'fragments/form_themes/_materialize.html.twig'
    globals:
        site_name: '%app_site_name%'

when@test:
    twig:
        strict_variables: true