vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: /images/dynamic/products
            upload_destination: '%kernel.project_dir%/public/images/dynamic/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        delivery_method_images:
            uri_prefix: /images/dynamic/delivery-methods
            upload_destination: '%kernel.project_dir%/public/images/dynamic/delivery-methods'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        payment_method_images:
            uri_prefix: /images/dynamic/payment-methods
            upload_destination: '%kernel.project_dir%/public/images/dynamic/payment-methods'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true