name: app

type: php:7.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - soap
        

variables:
    env:
        APP_ENV: 'prod'
        APP_DEBUG: 0
    php:
        # uncomment on PHP 7.4+
        opcache.preload: /app/config/preload.php

build:
    flavor: composer

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

relationships:
    mysql_database: "database:mysql"

dependencies:
    php:
        composer/composer: '^2'
    nodejs:
        yarn: "*"

mounts:
    "/var": { source: local, source_path: var }
    "/public/images": "shared:files/images"

hooks:
    build: |
        set -x -e

        yarn install --ignore-engines

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)

        (>&2 symfony-build)

        yarn build

    deploy: |
        set -x -e

        rm -rf var/cache/*

        (>&2 symfony-deploy)
