#index:
#    path: /
#    controller: App\Controller\DefaultController::index

oauth_check:
    path: /oauth/check/{service<facebook|google>}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
