# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_site_name: 'Šperky'
    app_site_phone: '+420 123 456 789'
    app_site_email: 'demo@localhost.com'
    app_site_facebook: 'https://www.facebook.com'
    app_site_instagram: 'https://www.instagram.com'
    app_email_noreply: 'noreply@sperky-test.cz'
    app_email_verify_link_throttle_limit: 600 # seconds

    # route titles
    app_page_title.home: 'Domů'
    app_page_title.contact: 'Kontakt'
    app_page_title.profile: 'Osobní údaje'
    app_page_title.profile_change_password: 'Změna hesla'
    app_page_title.profile_verify: 'Ověření emailu'
    app_page_title.profile_addresses: 'Adresy'
    app_page_title.profile_address:
        new: 'Nová adresa'
        edit: 'Upravit adresu'
    app_page_title.profile_address_delete: 'Smazat adresu'
    app_page_title.reviews: 'Recenze'
    app_page_title.review_edit:
        new: 'Nová recenze'
        edit: 'Upravit recenzi'
    app_page_title.review_delete: 'Smazat recenzi'
    app_page_title.forgot_password_request: 'Obnova hesla'
    app_page_title.check_email: 'Potvrzení obnovy hesla'
    app_page_title.reset_password: 'Obnova hesla'
    app_page_title.register: 'Registrace'
    app_page_title.login: 'Přihlášení'
    app_page_title.admin_permission_overview: 'Moje oprávnění'
    app_page_title.admin_user_management: 'Uživatelé'
    app_page_title.admin_user_management_specific: 'Uživatel'
    app_page_title.admin_product_sections: 'Produktové sekce'
    app_page_title.admin_product_section_edit:
        new: 'Nová produktová sekce'
        edit: 'Upravit produktovou sekci'
    app_page_title.admin_product_section_delete: 'Smazat produktovou sekci'
    app_page_title.admin_product_categories: 'Produktové kategorie'
    app_page_title.admin_product_category_edit:
        new: 'Nová skupina produktových kategorií'
        edit: 'Upravit skupinu produktových kategorií'
    app_page_title.admin_product_category_delete: 'Smazat skupinu produktových kategorií'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones