parameters:
    # všeobecné
    app_vat_payer: false
    app_site_name: 'Prysky'
    app_site_phone: '+420 123 456 789'
    app_site_email: 'demo@localhost.com'
    app_site_facebook: 'https://www.facebook.com'
    app_site_instagram: 'https://www.instagram.com'
    app_email_noreply: 'noreply@prysky.cz'
    app_email_verify_throttling_interval: 300 # sekund (5 minut)
    app_packeta_api_url: 'https://www.zasilkovna.cz/api/soap-php-bugfix.wsdl'
    app_packeta_key: '%env(PACKETA_KEY)%'
    app_packeta_secret: '%env(PACKETA_SECRET)%'
    container.dumper.inline_factories: true

    # GoPay
    gopay.config:
        goid: '%env(GOPAY_ID)%'
        clientId: '%env(GOPAY_CLIENT_ID)%'
        clientSecret: '%env(GOPAY_CLIENT_SECRET)%'
        gatewayUrl: '%env(GOPAY_GATEWAY_URL)%'
        scope: payment-all
        language: CS
        timeout: 30

    # synchronizátor košíku
    app_cart:
        synchronize_at: ['cart_insert', 'cart_update', 'cart_remove', 'order_cart', 'order_methods', 'order_addresses']

    # textový obsah
    app_text_content:
        default_text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris metus. Nunc tincidunt ante vitae massa. In enim a arcu imperdiet malesuada. Curabitur vitae diam non enim vestibulum interdum. Nunc dapibus tortor vel mi dapibus sollicitudin.'
        routes:
            _all: ['footer_about']
            home: ['home_what_we_do', 'home_follow_us']

    # skupiny admin oprávnění
    app_permission_category.reviews: 'Recenze'
    app_permission_category.users: 'Uživatelé'
    app_permission_category.orders: 'Objednávky'
    app_permission_category.products: 'Produkty'
    app_permission_category.product_sections: 'Produktové sekce'
    app_permission_category.product_categories: 'Produktové kategorie'
    app_permission_category.product_options: 'Produktové volby'
    app_permission_category.product_info: 'Skupiny produktových informací'
    app_permission_category.delivery_payment_methods: 'Doručovací a platební metody'

    # admin oprávnění (po editaci je nutné vyvolat "php bin/console app:refresh-permissions" pro aktualizaci v DB)
    app_permissions:
        review_edit:
            name: 'Editace recenzí'
            category: '%app_permission_category.reviews%'
        review_delete:
            name: 'Mazání recenzí'
            category: '%app_permission_category.reviews%'

        user_edit_credentials:
            name: 'Editace osobních údajů uživatelů'
            category: '%app_permission_category.users%'
        user_block_reviews:
            name: 'Zablokování možnosti napsání recenze uživatelů'
            category: '%app_permission_category.users%'
        user_set_permissions:
            name: 'Nastavení oprávnění uživatelů'
            category: '%app_permission_category.users%'

        product_section_edit:
            name: 'Tvorba a editace produktových sekcí'
            category: '%app_permission_category.product_sections%'
        product_section_delete:
            name: 'Mazání produktových sekcí'
            category: '%app_permission_category.product_sections%'

        product_category_edit:
            name: 'Tvorba a editace produktových kategorií'
            category: '%app_permission_category.product_categories%'
        product_category_delete:
            name: 'Mazání produktových kategorií'
            category: '%app_permission_category.product_categories%'

        product_option_edit:
            name: 'Tvorba a editace produktových voleb'
            category: '%app_permission_category.product_options%'
        product_option_delete:
            name: 'Mazání produktových voleb'
            category: '%app_permission_category.product_options%'

        product_info_edit:
            name: 'Tvorba a editace skupin produktových informací'
            category: '%app_permission_category.product_info%'
        product_info_delete:
            name: 'Mazání skupin produktových informací'
            category: '%app_permission_category.product_info%'

        product_edit:
            name: 'Tvorba a editace produktů'
            category: '%app_permission_category.products%'
        product_delete:
            name: 'Mazání produktů'
            category: '%app_permission_category.products%'

        delivery_method_edit:
            name: 'Editace doručovacích metod'
            category: '%app_permission_category.delivery_payment_methods%'
        payment_method_edit:
            name: 'Editace platebních metod'
            category: '%app_permission_category.delivery_payment_methods%'

        order_edit:
            name: 'Editace objednávek'
            category: '%app_permission_category.orders%'
        order_cancel:
            name: 'Rušení objednávek'
            category: '%app_permission_category.orders%'
        order_edit_custom:
            name: 'Tvorba a editace objednávek na míru'
            category: '%app_permission_category.orders%'
        order_delete_custom:
            name: 'Mazání objednávek na míru'
            category: '%app_permission_category.orders%'

    # sekce v administraci
    app_admin_routes_required_permissions:
        admin_dashboard: '_any'
        admin_user_management: ['user_edit_credentials', 'user_block_reviews', 'user_set_permissions']
        admin_orders: ['order_edit', 'order_cancel', 'order_edit_custom', 'order_delete_custom']
        admin_products: ['product_edit', 'product_delete']
        admin_product_sections: ['product_section_edit', 'product_section_delete']
        admin_product_categories: ['product_category_edit', 'product_category_delete']
        admin_product_options: ['product_option_edit', 'product_option_delete']
        admin_product_info: ['product_info_edit', 'product_info_delete']
        admin_delivery_methods: ['delivery_method_edit']
        admin_payment_methods: ['payment_method_edit']

    # názvy cest
    app_page_title.home: 'Domů'
    app_page_title.contact: 'Kontakt'
    app_page_title.profile: 'Osobní údaje'
    app_page_title.profile_change_password: 'Změna hesla'
    app_page_title.profile_orders: 'Historie objednávek'
    app_page_title.profile_order: 'Objednávka'
    app_page_title.profile_addresses: 'Adresy'
    app_page_title.profile_address:
        new: 'Nová adresa'
        edit: 'Upravit adresu'
    app_page_title.profile_address_delete: 'Smazat adresu'
    app_page_title.reviews: 'Všechny recenze'
    app_page_title.review_edit:
        new: 'Nová recenze'
        edit: 'Upravit recenzi'
    app_page_title.review_delete: 'Smazat recenzi'
    app_page_title.forgot_password_request: 'Obnova hesla'
    app_page_title.reset_password: 'Nové heslo'
    app_page_title.register: 'Registrace'
    app_page_title.login: 'Přihlášení'
    app_page_title.verify_email: 'Ověřit email'
    app_page_title.products: 'Všechny produkty'
    app_page_title.product: 'Produkt'
    app_page_title.order_cart: 'Košík'
    app_page_title.order_custom: 'Objednávka na míru'
    app_page_title.order_custom_new: 'Objednávka na míru'
    app_page_title.order_methods: 'Doprava a platba'
    app_page_title.order_addresses: 'Dodací údaje'
    app_page_title.order_overview: 'Objednávka'
    app_page_title.payment_return: 'Platba'
    app_page_title.admin_dashboard: 'Dashboard'
    app_page_title.admin_user_management: 'Uživatelé'
    app_page_title.admin_user_management_specific: 'Uživatel'
    app_page_title.admin_product_sections: 'Produktové sekce'
    app_page_title.admin_product_section_edit:
        new: 'Nová produktová sekce'
        edit: 'Upravit produktovou sekci'
    app_page_title.admin_product_section_delete: 'Smazat produktovou sekci'
    app_page_title.admin_product_categories: 'Produktové kategorie'
    app_page_title.admin_product_category_edit:
        new: 'Nová skupina produktových kategorií'
        edit: 'Upravit skupinu produktových kategorií'
    app_page_title.admin_product_category_delete: 'Smazat skupinu produktových kategorií'
    app_page_title.admin_product_options: 'Produktové volby'
    app_page_title.admin_product_option_edit:
        new: 'Nová skupina produktových voleb'
        edit: 'Upravit skupinu produktových voleb'
    app_page_title.admin_product_option_delete: 'Smazat skupinu produktových voleb'
    app_page_title.admin_product_info: 'Produktové informace'
    app_page_title.admin_product_info_edit:
        new: 'Nová skupina produktových informací'
        edit: 'Upravit skupinu produktových informací'
    app_page_title.admin_product_info_delete: 'Smazat skupinu produktových informací'
    app_page_title.admin_products: 'Produkty'
    app_page_title.admin_product_edit:
        new: 'Nový produkt'
        edit: 'Upravit produkt'
    app_page_title.admin_product_delete: 'Smazat produkt'
    app_page_title.admin_delivery_methods: 'Doručovací metody'
    app_page_title.admin_delivery_method_edit: 'Upravit doručovací metodu'
    app_page_title.admin_payment_methods: 'Platební metody'
    app_page_title.admin_payment_method_edit: 'Upravit platební metodu'
    app_page_title.admin_orders: 'Objednávky'
    app_page_title.admin_order_overview: 'Objednávka'
    app_page_title.admin_order_cancel: 'Zrušit objednávku'
    app_page_title.admin_order_custom_delete: 'Smazat objednávku na míru'
    app_page_title.admin_order_custom_edit:
        new: 'Nová objednávka na míru'
        edit: 'Upravit objednávku na míru'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Pagination/'
            - '../src/Messenger/'
            - '../src/Exception/'
            - '../src/Response/'
            - '../src/CatalogFilter/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\EventSubscriber\DoctrineTrackingPolicySubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    gopay.payments:
        class: GoPay\Payments
        factory: ['GoPay\Api', payments]
        arguments:
            - '%gopay.config%'
            - cache: '@gopay.cache'

    gopay.cache:
        class: GoPay\Token\InMemoryTokenCache

    app.navbar_service:
        class: App\Service\Navbar
    app.cart_service:
        class: App\Service\Cart
    app.breadcrumbs_service:
        class: App\Service\Breadcrumbs
    app.packeta_service:
        class: App\Service\Packeta

    App\Service\Navbar: '@app.navbar_service'
    App\Service\Cart: '@app.cart_service'
    App\Service\Breadcrumbs: '@app.breadcrumbs_service'
    App\Service\Packeta: '@app.packeta_service'
    GoPay\Payments: '@gopay.payments'