parameters:
    app_vat_payer: false
    app_site_name: 'Prysky'
    app_site_phone: '+420 123 456 789'
    app_site_email: 'demo@localhost.com'
    app_site_facebook: 'https://www.facebook.com'
    app_site_instagram: 'https://www.instagram.com'
    app_email_noreply: 'noreply@prysky.cz'
    app_email_verify_throttling_interval: 300 # sekund (5 minut)
    app_packeta_api_url: 'https://www.zasilkovna.cz/api/soap-php-bugfix.wsdl'
    app_packeta_key: '%env(PACKETA_KEY)%'
    app_packeta_secret: '%env(PACKETA_SECRET)%'

    gopay.config:
        goid: '%env(GOPAY_ID)%'
        clientId: '%env(GOPAY_CLIENT_ID)%'
        clientSecret: '%env(GOPAY_CLIENT_SECRET)%'
        gatewayUrl: '%env(GOPAY_GATEWAY_URL)%'
        # optional config
        scope: payment-all
        language: CS
        timeout: 30

    container.dumper.inline_factories: true

    # názvy cest
    app_page_title.home: 'Domů'
    app_page_title.contact: 'Kontakt'
    app_page_title.profile: 'Osobní údaje'
    app_page_title.profile_change_password: 'Změna hesla'
    app_page_title.profile_orders: 'Historie objednávek'
    app_page_title.profile_order: 'Objednávka'
    app_page_title.profile_addresses: 'Adresy'
    app_page_title.profile_address:
        new: 'Nová adresa'
        edit: 'Upravit adresu'
    app_page_title.profile_address_delete: 'Smazat adresu'
    app_page_title.reviews: 'Všechny recenze'
    app_page_title.review_edit:
        new: 'Nová recenze'
        edit: 'Upravit recenzi'
    app_page_title.review_delete: 'Smazat recenzi'
    app_page_title.forgot_password_request: 'Obnova hesla'
    app_page_title.reset_password: 'Nové heslo'
    app_page_title.register: 'Registrace'
    app_page_title.login: 'Přihlášení'
    app_page_title.verify_email: 'Ověřit email'
    app_page_title.products: 'Všechny produkty'
    app_page_title.product: 'Produkt'
    app_page_title.order_cart: 'Košík'
    app_page_title.order_custom: 'Objednávka na míru'
    app_page_title.order_custom_new: 'Objednávka na míru'
    app_page_title.order_methods: 'Doprava a platba'
    app_page_title.order_addresses: 'Dodací údaje'
    app_page_title.order_overview: 'Objednávka'
    app_page_title.payment_return: 'Platba'
    app_page_title.admin_dashboard: 'Dashboard'
    app_page_title.admin_user_management: 'Uživatelé'
    app_page_title.admin_user_management_specific: 'Uživatel'
    app_page_title.admin_product_sections: 'Produktové sekce'
    app_page_title.admin_product_section_edit:
        new: 'Nová produktová sekce'
        edit: 'Upravit produktovou sekci'
    app_page_title.admin_product_section_delete: 'Smazat produktovou sekci'
    app_page_title.admin_product_categories: 'Produktové kategorie'
    app_page_title.admin_product_category_edit:
        new: 'Nová skupina produktových kategorií'
        edit: 'Upravit skupinu produktových kategorií'
    app_page_title.admin_product_category_delete: 'Smazat skupinu produktových kategorií'
    app_page_title.admin_product_options: 'Produktové volby'
    app_page_title.admin_product_option_edit:
        new: 'Nová skupina produktových voleb'
        edit: 'Upravit skupinu produktových voleb'
    app_page_title.admin_product_option_delete: 'Smazat skupinu produktových voleb'
    app_page_title.admin_product_info: 'Produktové informace'
    app_page_title.admin_product_info_edit:
        new: 'Nová skupina produktových informací'
        edit: 'Upravit skupinu produktových informací'
    app_page_title.admin_product_info_delete: 'Smazat skupinu produktových informací'
    app_page_title.admin_products: 'Produkty'
    app_page_title.admin_product_edit:
        new: 'Nový produkt'
        edit: 'Upravit produkt'
    app_page_title.admin_product_delete: 'Smazat produkt'
    app_page_title.admin_delivery_methods: 'Doručovací metody'
    app_page_title.admin_delivery_method_edit: 'Upravit doručovací metodu'
    app_page_title.admin_payment_methods: 'Platební metody'
    app_page_title.admin_payment_method_edit: 'Upravit platební metodu'
    app_page_title.admin_orders: 'Objednávky'
    app_page_title.admin_order_overview: 'Objednávka'
    app_page_title.admin_order_cancel: 'Zrušit objednávku'
    app_page_title.admin_order_custom_delete: 'Smazat objednávku na míru'
    app_page_title.admin_order_custom_edit:
        new: 'Nová objednávka na míru'
        edit: 'Upravit objednávku na míru'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Pagination/'
            - '../src/Messenger/'
            - '../src/Exception/'
            - '../src/Response/'
            - '../src/CatalogFilter/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\EventSubscriber\DoctrineTrackingPolicySubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    gopay.payments:
        class: GoPay\Payments
        factory: ['GoPay\Api', payments]
        arguments:
            - '%gopay.config%'
            - cache: '@gopay.cache'

    gopay.cache:
        class: GoPay\Token\InMemoryTokenCache

    app.navbar_service:
        class: App\Service\NavbarService
    app.cart_service:
        class: App\Service\CartService
    app.breadcrumbs_service:
        class: App\Service\BreadcrumbsService
    app.packeta_service:
        class: App\Service\PacketaApiService

    App\Service\NavbarService: '@app.navbar_service'
    App\Service\CartService: '@app.cart_service'
    App\Service\BreadcrumbsService: '@app.breadcrumbs_service'
    App\Service\PacketaApiService: '@app.packeta_service'
    GoPay\Payments: '@gopay.payments'